return {
	-- 	"akinsho/bufferline.nvim",
	-- 	version = "*",
	-- 	dependencies = "nvim-tree/nvim-web-devicons",
	-- 	config = function()
	-- 		require("bufferline").setup({
	-- 			options = {
	-- 				mode = "buffers", -- This makes it behave like VS Code
	-- 				separator_style = "slant", -- Cool visual look
	-- 				offsets = {
	-- 					{
	-- 						filetype = "NvimTree",
	-- 						text = "File Explorer",
	-- 						text_align = "left",
	-- 						separator = true,
	-- 					},
	-- 				},
	-- 			},
	-- 		})
	-- 	end,
}
